### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by Aibotopup** [biobios/blogger_theme#1]
please update to english version and fix some bugs

**Comment by biobios** [comment]
Thank you for your feedback and I apologize for the delayed response.

Could you please provide more details about the bugs you've encountered? This information will help me address and fix them more effectively.

Additionally, I plan to work on an English version soon. Your patience and understanding are greatly appreciated.

Best regards,

BioBIOS

_This message was generated with the help of ChatGPT._

**Comment by biobios** [comment]
I have released the English version, so I will close this issue.
